- name: Prideti nauja vartotoja ir grupe
  hosts: test
  become: true
  become_method: sudo
  vars:
    users: 
    - username: "testas1"
      groups: "semaphore_test"
    - username: "testas2"
      groups: "semaphore_test"
  tasks:
    - name: Create group
      group:
        name: "{{ item.groups }}"
        state: present
      with_items: "{{ users }}"

    - name: Create Users Task
      user:
        name: "{{ item.username }}"
        state: absent
        shell: /bin/bash
        group: "{{ item.groups }}"
      with_items: "{{ users }}"

    - name: Create sn SSH key for user {{ theName }}
      ansible.builtin.user:
       name: “{{ item.username }}”
       state: absent
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa
      with_items: "{{ users }}"
