- name: Prideti nauja vartotoja ir grupe
  hosts: test
  become: true
  become_method: sudo
  vars:
    theName: 
    - testas1
    - testas2
    grupe: sempahore_test
  tasks:
    - name: Create group
      group:
        name: "{{ grupe }}"
        state: present

    - name: Create Users Task
      user:
        name: "{{ theName }}"
        state: present
        shell: /bin/bash
        group: "{{ grupe }}"
