    hosts: test
    become: true
    become_method: sudo
    vars:
        theName: testas1
        tasks:
        - name: Sukuriam grupe pavadinimu semaphore_test
          group:
            name: "{{ semaphore_test }}"
            state: present
    – name: Task to add a new user
    ansible.builtin.user:
        name: “{{ theName }}”
        state: present
        shell: /bin/bash
        group: "{{ semaphore_test }}"
