    – name: Playbook to add a new user
    hosts: test
    vars:
    theName: testas1
    tasks:
        - name: Sukuriam grupe pavadinimu semaphore_test
          group:
            name: "{{ semaphore_test }}"
            state: present
    – name: Task to add a new user
    ansible.builtin.user:
        name: “{{ theName }}”
        state: present
        shell: /bin/bash
        group: "{{ semaphore_test }}"
    – name: Tast to check information in user home folder
    ansible.builtin.command:
        cmd: “ls -A /home/{{ theName }}”
        register: results
    – name: Display the listing of home directory
    ansible.builtin.debug:
        var: results.stdout
    – name: Create sn SSH key for user {{ theName }}
    ansible.builtin.user:
        name: “{{ theName }}”
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
    – name: Tast again to check information in user home folder
    ansible.builtin.command:
        cmd: “ls -A /home/{{ theName }}”
        register: newResults

        – name: Display the listing of home directory to see if ssh folder was created
            ansible.builtin.debug:
                var: newResults.stdout
