- name: Prideti nauja vartotoja ir grupe
  hosts: test
  become: true
  become_method: sudo
  vars:
    theName: testas1
  tasks:
    - name: Create group
      group:
        name: "{{ semaphore_test }}"
        state: present

    - name: Create Users Task
      user:
        name: "{{ theName }}"
        state: present
        shell: /bin/bash
        group: "{{ semaphore_test }}"
      
