---
- name: Configure Apache2 with SSL and force redirect from IP to hostname
  hosts: test
  become: yes
  become_method: sudo

  tasks:
    - name: Nustatyti hostname
      hostname:
        name: test.test.lt

    - name: Įtraukti į /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "192.168.195.102 test.test.lt"
        state: present

    - name: Įdiegti Apache2 ir OpenSSL
      apt:
        name:
          - apache2
          - openssl
        state: present
        update_cache: yes

    - name: Sukurti SSL direktoriją
      file:
        path: /etc/apache2/ssl
        state: directory
        mode: '0755'

    - name: Generuoti SSL sertifikatus
      shell: |
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /etc/apache2/ssl/test.test.lt.key \
          -out /etc/apache2/ssl/test.test.lt.crt \
          -subj "/C=LT/ST=State/L=City/O=Organization/OU=Department/CN=test.test.lt"
      args:
        creates: /etc/apache2/ssl/test.test.lt.crt

    - name: Konfigūruoti Apache virtual hostus
      copy:
        dest: /etc/apache2/sites-available/default-ssl.conf
        content: |
          # Peradresavimas iš HTTP į HTTPS
          <VirtualHost *:80>
              ServerName test.test.lt
              Redirect permanent / https://test.test.lt/
          </VirtualHost>

          # Peradresavimas iš IP adresu pasiekto HTTP į HTTPS
          <VirtualHost *:80>
              ServerName 192.168.195.102
              Redirect permanent / https://test.test.lt/
          </VirtualHost>

          # Peradresavimas iš IP adresu pasiekto HTTPS į hostname
          <VirtualHost *:443>
              ServerName 192.168.195.102
              SSLEngine on
              SSLCertificateFile /etc/apache2/ssl/test.test.lt.crt
              SSLCertificateKeyFile /etc/apache2/ssl/test.test.lt.key
              Redirect permanent / https://test.test.lt/
          </VirtualHost>

          # Pagrindinis HTTPS VirtualHost su hostname
          <VirtualHost *:443>
              ServerName test.test.lt
              DocumentRoot /var/www/html
              SSLEngine on
              SSLCertificateFile /etc/apache2/ssl/test.test.lt.crt
              SSLCertificateKeyFile /etc/apache2/ssl/test.test.lt.key
          </VirtualHost>

    - name: Sukurti testinį index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Apache testas su SSL ir IP redirect</h1>"
        mode: '0644'

    - name: Įjungti SSL modulį ir virtualų hostą
      shell: |
        a2enmod ssl
        a2enconf ssl
        a2ensite default-ssl.conf
        systemctl restart apache2
      notify: Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
