- name: Konfiguracija apache su SSL
  hosts: test
  become: yes
  tasks:
    - name: Update package cache 
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install apache2 ir openssl 
      package:
        name:
          - apache2
          - openssl
        state: present

    - name: Apache start
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Generuojam SSL
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /etc/ssl/private/apache-selfsigned.key
        -out /etc/ssl/certs/apache-selfsigned.crt
        -subj "/C=US/ST=State/L=City/O=Organization/CN=192.168.195.104"
      args:
        creates: /etc/ssl/certs/apache-selfsigned.crt

    - name: Apache virtual hostai
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              ServerName 192.168.195.104
              Redirect permanent / https://192.168.195.104/
          </VirtualHost>
          <VirtualHost *:443>
              ServerName 192.168.195.104
              DocumentRoot /var/www/html
              SSLEngine on
              SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
              SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
          </VirtualHost>
        mode: '0644'
      notify: Restart Apache

    - name: Enable Apache SSL 
      command: a2enmod ssl
      notify: Restart Apache

    - name: Enable Apache Rewrite 
      command: a2enmod rewrite
      notify: Restart Apache

    - name: Enable new site config
      command: a2ensite 000-default.conf
      notify: Restart Apache

    - name: Pavyzdinis index
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Apache testas su SSL</h1>"
        mode: '0644'

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
