- name: Setup Apache Web Server with Self-Signed SSL
  hosts: db
  become: yes
  tasks:
    - name: Update package cache (Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache2 and OpenSSL
      package:
        name:
          - apache2
          - openssl
        state: present

    - name: Ensure Apache is running before configuring SSL
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Generate a self-signed SSL certificate
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout /etc/ssl/private/apache-selfsigned.key
        -out /etc/ssl/certs/apache-selfsigned.crt
        -subj "/C=US/ST=State/L=City/O=Organization/CN=192.168.195.103"
      args:
        creates: /etc/ssl/certs/apache-selfsigned.crt

    - name: Create Apache Virtual Host configuration file with SSL
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              ServerName 192.168.195.103
              Redirect permanent / https://192.168.195.103/
          </VirtualHost>
          <VirtualHost *:443>
              ServerName 192.168.195.103
              DocumentRoot /var/www/html
              SSLEngine on
              SSLCertificateFile /etc/ssl/certs/apache-selfsigned.crt
              SSLCertificateKeyFile /etc/ssl/private/apache-selfsigned.key
          </VirtualHost>
        mode: '0644'
      notify: Restart Apache

    - name: Enable Apache SSL module
      command: a2enmod ssl
      notify: Restart Apache

    - name: Enable Apache Rewrite module
      command: a2enmod rewrite
      notify: Restart Apache

    - name: Enable the new site configuration
      command: a2ensite 000-default.conf
      notify: Restart Apache

    - name: Create a sample index.html file
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to Apache Web Server with Self-Signed SSL</h1>"
        mode: '0644'

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
