---
- name: Setup Apache Web Server with SSL (Let's Encrypt)
  hosts: web
  become: yes
  tasks:
    - name: Update package cache (Debian-based systems)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Apache2 and required packages
      package:
        name:
          - apache2
          - certbot
          - python3-certbot-apache
        state: present

    - name: Ensure Apache is running before requesting SSL certificate
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Obtain SSL certificate from Let's Encrypt
      command: certbot --apache --non-interactive --agree-tos --email admin@192.168.195.103 -d 192.168.195.103
      args:
        creates: /etc/letsencrypt/live/192.168.195.103/fullchain.pem
      notify: Restart Apache

    - name: Create Apache Virtual Host configuration file with SSL
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              ServerName 192.168.195.103
              Redirect permanent / https://192.168.195.103/
          </VirtualHost>
          <VirtualHost *:443>
              ServerName 192.168.195.103
              DocumentRoot /var/www/html
              SSLEngine on
              SSLCertificateFile /etc/letsencrypt/live/192.168.195.103/fullchain.pem
              SSLCertificateKeyFile /etc/letsencrypt/live/192.168.195.103/privkey.pem
          </VirtualHost>
        mode: '0644'
      notify: Restart Apache

    - name: Enable Apache SSL module
      command: a2enmod ssl
      notify: Restart Apache

    - name: Enable Apache Rewrite module
      command: a2enmod rewrite
      notify: Restart Apache

    - name: Enable the new site configuration
      command: a2ensite 000-default.conf
      notify: Restart Apache

    - name: Setup automatic SSL renewal
      cron:
        name: "Renew Let's Encrypt SSL"
        job: "certbot renew --quiet"
        state: present
        special_time: daily

    - name: Create a sample index.html file
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to Apache Web Server with SSL</h1>"
        mode: '0644'

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
