- name: Install and configure auditd
  hosts: debian
  become: true
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install auditd and audispd-plugins
      apt:
        name:
          - auditd
   #       - audispd-plugins
        state: present

    - name: Kopijuojam rules pagal Linux architectura
      copy:
        src: "/etc/ansible/audit.rules_{{ ansible_architecture }}"
        dest: /etc/audit/rules.d/audit.rules
      when: ansible_architecture in ['i386', 'amd64']  # i386 is the 32-bit architecture, amd64 is the 64-bit one

    - name: Restart auditd service
      systemd:
        name: auditd
        state: restarted
        enabled: yes
