  name: Install aps
  hosts: test
  become: true
  become_method: sudo
  tasks:
    - name: Install tools
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - vim
        - net-tools
        - htop
        - atop
        - tcpdump
