---
- name: Panaikinti prisijungima slaptazodziu, galima prisijungti tik SSH
  hosts: test
  become: yes
  tasks:
    - name: Isjungiu prisijumgima slaptazodziu
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify:
        - restart sshd

    - name: Tuscio slaptazodzio blokavimas
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitEmptyPasswords'
        line: 'PermitEmptyPasswords no'
      notify:
        - restart sshd

    - name: ChallengeResponseAuthentication isjungimas
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication no'
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
