- hosts: test
  become: true
  become_method: sudo
tasks:
   - name: create group1
     group:
      name: cloudnloud
      state: present
   - name: create users
     user:
      name: fawaz 
      comment: admin
      groups: cloudnloud
