- hosts: test
  become: true
  become_method: sudo
  vars:
    users:
      - "testas1"
tasks:
   - name: create group1
     group:
      name: cloudnloud
      state: present
   - name: create users
     user:
      name: fawaz 
      comment: admin
      groups: cloudnloud
