- hosts: test
  become: true
  become_method: sudo
  vars:
    users:
      - "testas1"
      - "testas2"
  tasks:
   - name: sukurti grupe
     group:
       name: semaphore_test
       state: present
   - name: "create users"
     user:
       name:  "{{ item }}"
       groups: semaphore_test
      with_items: "{{ users }}"
    - name: "Add authorized keys"
        authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers" # path: in version 2.3
        state: "present"
        regexp: "^%semaphore_test"
