- name: creating users and groups and ssh connection
  hosts: test
  become: yes
  tasks:
   - user:
      name: "{{ item }}"
      state: present
     loop:
      - testas1
      - testas2
   - group:
      name: "{{ item }}"
      state: present
     loop:
      - semaphore_testas

   - ansible.builtin.user:
      name: test1
      shell: /bin/bash
      groups: semaphore_testas
      append: yes
      
   - ansible.builtin.user:
      name: test2
      shell: /bin/bash
      groups: semaphore_testas
      append: yes

   - authorized_key:
       user: test1
       state: present
       key: "{{ lookup('file', './user_id_rsa.pub') }}"

   - authorized_key:
       user: test2
       state: present
       key: "{{ lookup('file', './user_id_rsa.pub') }}"
