- hosts: test
  become: true
  become_method: sudo
  vars:
    users:
      - "testas"

  tasks:
    - name: "Create user accounts"
      user:
        name: "{{ item }}"
        groups: "admin,www-data"
      with_items: "{{ users }}"
    - name: "Add authorized keys"
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"
    - name: "Leisti sempahore vartotojams naudoti SSH be PSW"
      lineinfile:
        dest: "/etc/sudoers" 
        state: "present"
        regexp: "^%admin"
        line: "%admin ALL=(ALL) NOPASSWD: ALL"
