- hosts: test
  become: true
  become_method: sudo
  tasks:
   - name: sukurti grupe
     group:
       name: semaphore_test
       state: present
    - name: Add several users
      ansible.builtin.user:
      name: "{{ item }}"
      state: present
      groups: "wheel"
      loop:
        - testas1
        - testas2
    - name: "Add authorized keys"
        authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', 'files/'+ item + '.key.pub') }}"
      with_items: "{{ users }}"
    - name: "Allow admin users to sudo without a password"
      lineinfile:
        dest: "/etc/sudoers" # path: in version 2.3
        state: "present"
        regexp: "^%semaphore_test"
