---
- name: Configure Apache2 with SSL and set hostname
  hosts: test
  become: yes

  tasks:
    - name: Set hostname
      hostname:
        name: test.test.lt

    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "192.168.195.102 test.test.lt"
        state: present

    - name: Install Apache2 and OpenSSL
      apt:
        name:
          - apache2
          - openssl
        state: present
        update_cache: yes

    - name: Create SSL directory
      file:
        path: /etc/apache2/ssl
        state: directory
        mode: '0755'

    - name: Generate SSL certificate
      shell: |
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /etc/apache2/ssl/test.test.lt.key \
          -out /etc/apache2/ssl/test.test.lt.crt \
          -subj "/C=LT/ST=State/L=City/O=Organization/OU=Department/CN=test.test.lt"
      args:
        creates: /etc/apache2/ssl/test.test.lt.crt

    - name: Configure Apache to use SSL
      copy:
        dest: /etc/apache2/sites-available/test.test.lt.conf
        content: |
          <VirtualHost *:443>
              ServerName test.test.lt
              DocumentRoot /var/www/html
              SSLEngine on
              SSLCertificateFile /etc/apache2/ssl/test.test.lt.crt
              SSLCertificateKeyFile /etc/apache2/ssl/test.test.lt.key
          </VirtualHost>

    - name: Enable SSL module and site
      shell: |
        a2enmod ssl
        a2ensite test.test.lt.conf
        systemctl restart apache2
