---
- name: Setup Apache2 with SSL for test.test.lt
  hosts: test
  become: yes
  vars:
    domain_name: "test.test.lt"
    server_ip: "192.168.195.102"
    ssl_cert_path: "/etc/apache2/ssl/test.crt"
    ssl_key_path: "/etc/apache2/ssl/test.key"
    web_root: "/var/www/test.test.lt"

  tasks:
    - name: Install Apache2 and OpenSSL
      apt:
        name:
          - apache2
          - openssl
        state: present
        update_cache: yes

    - name: Create SSL directory
      file:
        path: "/etc/apache2/ssl"
        state: directory
        mode: '0755'

    - name: Generate SSL certificate and key
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout {{ ssl_key_path }} -out {{ ssl_cert_path }}
        -subj "/C=US/ST=State/L=City/O=Organization/CN={{ domain_name }}"

    - name: Create website directory
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create index.html file
      copy:
        dest: "{{ web_root }}/index.html"
        content: "<h1>Welcome to {{ domain_name }}!</h1>"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configure Apache Virtual Host
      copy:
        dest: "/etc/apache2/sites-available/{{ domain_name }}.conf"
        content: |
          <VirtualHost *:80>
              ServerName {{ domain_name }}
              Redirect permanent / https://{{ domain_name }}/
          </VirtualHost>

          <VirtualHost *:443>
              ServerAdmin admin@{{ domain_name }}
              ServerName {{ domain_name }}

              DocumentRoot {{ web_root }}
              <Directory {{ web_root }}>
                  AllowOverride All
                  Require all granted
              </Directory>

              SSLEngine on
              SSLCertificateFile {{ ssl_cert_path }}
              SSLCertificateKeyFile {{ ssl_key_path }}

              ErrorLog ${APACHE_LOG_DIR}/{{ domain_name }}_error.log
              CustomLog ${APACHE_LOG_DIR}/{{ domain_name }}_access.log combined
          </VirtualHost>
      notify: Restart Apache

    - name: Enable Apache SSL module
      command: a2enmod ssl
      notify: Restart Apache

    - name: Enable site configuration
      command: a2ensite {{ domain_name }}.conf
      notify: Restart Apache

    - name: Ensure Apache is running
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Add domain entry to /etc/hosts (on remote server)
      lineinfile:
        path: /etc/hosts
        line: "{{ server_ip }} {{ domain_name }}"
        state: present

  handlers:
    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted
