---
- name: Setup Local DNS and Apache with SSL
  hosts: test
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - bind9
          - apache2
          - openssl
          - certbot
          - python3-certbot-apache
        state: present
        update_cache: yes

    - name: Configure BIND DNS Server
      copy:
        dest: /etc/bind/named.conf.local
        content: |
          zone "test.test.lt" {
              type master;
              file "/etc/bind/db.test.test.lt";
          };
      notify: Restart BIND

    - name: Create zone file for test.test.lt
      copy:
        dest: /etc/bind/db.test.test.lt
        content: |
          $TTL    604800
          @       IN      SOA     test.test.lt. root.test.test.lt. (
                              2         ; Serial
                          604800         ; Refresh
                           86400         ; Retry
                         2419200         ; Expire
                          604800 )       ; Negative Cache TTL
          ;
          @       IN      NS      test.test.lt.
          @       IN      A       192.168.195.102
          www     IN      A       192.168.195.102
      notify: Restart BIND

    - name: Enable Apache modules for SSL
      command: a2enmod ssl

    - name: Create virtual host for test.test.lt
      copy:
        dest: /etc/apache2/sites-available/test.test.lt.conf
        content: |
          <VirtualHost *:80>
              ServerName test.test.lt
              Redirect permanent / https://test.test.lt/
          </VirtualHost>

          <VirtualHost *:443>
              ServerName test.test.lt
              DocumentRoot /var/www/html

              SSLEngine on
              SSLCertificateFile /etc/letsencrypt/live/test.test.lt/fullchain.pem
              SSLCertificateKeyFile /etc/letsencrypt/live/test.test.lt/privkey.pem

              <Directory /var/www/html>
                  AllowOverride All
                  Require all granted
              </Directory>
          </VirtualHost>
      notify: Restart Apache

    - name: Enable Apache site configuration
      command: a2ensite test.test.lt
      notify: Restart Apache

    - name: Obtain SSL certificate using Certbot
      command: certbot --apache -d test.test.lt --non-interactive --agree-tos --email admin@test.test.lt
      
    - name: Pavyzdinis index
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Apache testas su SSL</h1>"
        mode: '0644'

  handlers:
    - name: Restart BIND
      service:
        name: bind9
        state: restarted

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
