---
- name: Install and configure Apache with SSL for test.test.lt
  hosts: test
  become: yes
  vars:
    domain: "test.test.lt"
    ssl_cert_path: "/etc/ssl/certs/{{ domain }}.crt"
    ssl_key_path: "/etc/ssl/private/{{ domain }}.key"
    use_letsencrypt: false  # Set to true if you want to use Let's Encrypt

  tasks:
    - name: Install required packages
      apt:
        name:
          - apache2
          - openssl
          - certbot
          - python3-certbot-apache
        state: present
        update_cache: yes

    - name: Enable required Apache modules
      shell: |
        a2enmod ssl
        a2enmod rewrite
      notify: Restart Apache

    - name: Generate a self-signed SSL certificate (if Let's Encrypt is not used)
      command: >
        openssl req -x509 -nodes -days 365 -newkey rsa:2048
        -keyout {{ ssl_key_path }}
        -out {{ ssl_cert_path }}
        -subj "/C=LT/ST=Test/L=Test/O=Test/OU=IT/CN={{ domain }}"
      args:
        creates: "{{ ssl_cert_path }}"
      when: not use_letsencrypt

    - name: Obtain Let's Encrypt SSL certificate
      command: certbot --apache -n --agree-tos --email admin@{{ domain }} -d {{ domain }}
      when: use_letsencrypt
      notify: Restart Apache

    - name: Configure Apache VirtualHost for HTTP (Redirect to HTTPS)
      copy:
        dest: "/etc/apache2/sites-available/{{ domain }}.conf"
        content: |
          <VirtualHost *:80>
              ServerName {{ domain }}
              Redirect permanent / https://{{ domain }}/
          </VirtualHost>
      notify: Restart Apache

    - name: Configure Apache VirtualHost for HTTPS
      copy:
        dest: "/etc/apache2/sites-available/{{ domain }}-ssl.conf"
        content: |
          <VirtualHost *:443>
              ServerName {{ domain }}
              SSLEngine on
              SSLCertificateFile {{ ssl_cert_path }}
              SSLCertificateKeyFile {{ ssl_key_path }}
              DocumentRoot /var/www/html
              <Directory /var/www/html>
                  AllowOverride All
              </Directory>
          </VirtualHost>
      notify: Restart Apache

    - name: Enable Apache site configurations
      shell: |
        a2ensite {{ domain }}.conf
        a2ensite {{ domain }}-ssl.conf
      notify: Restart Apache

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
