---
- name: Configure Apache2 with SSL and set hostname
  hosts: test
  become: yes
  become_method: sudo

  tasks:
    - name: Set hostname
      hostname:
        name: test.test.lt

    - name: Update /etc/hosts file
      lineinfile:
        path: /etc/hosts
        line: "192.168.195.102 test.test.lt"
        state: present

    - name: Install Apache2 and OpenSSL
      apt:
        name:
          - apache2
          - openssl
        state: present
        update_cache: yes

    - name: Create SSL directory
      file:
        path: /etc/apache2/ssl
        state: directory
        mode: '0755'

    - name: Generate SSL certificate
      shell: |
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout /etc/ssl/certs/test.test.lt.key \
          -out /etc/ssl/certs/test.test.lt.crt \
          -subj "/C=LT/ST=State/L=City/O=Organization/OU=Department/CN=test.test.lt" \
          -config /etc/ssl/openssl.cnf
      args:
        creates: /etc/ssl/certs/test.test.lt.crt

    - name: Apache virtual hostai
      copy:
        dest: /etc/apache2/sites-available/000-default.conf
        content: |
          <VirtualHost *:80>
              ServerName test.test.lt
              Redirect permanent / https://test.test.lt/
          </VirtualHost>
          <VirtualHost *:443>
              ServerName test.test.lt
              DocumentRoot /var/www/html
              SSLEngine on
              SSLCertificateFile /etc/ssl/certs/test.test.lt.crt
              SSLCertificateKeyFile /etc/ssl/certs/test.test.lt.key
          </VirtualHost>
          
    - name: Pavyzdinis index
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Apache testas su SSL</h1>"
        mode: '0644'
        
    - name: Enable SSL module and site
      shell: |
        a2enmod ssl
        a2ensite test.test.lt.conf
        systemctl restart apache2

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
