---
- name: Konfigūruoti iptables su būsenomis
  hosts: test
  become: true
  tasks:
    - name: Išvalyti esamas iptables taisykles
      iptables:
        flush: yes

    - name: Leisti input ryšius (SSH, HTTP, HTTPS, ZABBIX AGENT)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 10050

    - name: Log input ICMP echo užklausas
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: LOG
        log_prefix: "ICMP Echo request: "
        log_level: 4

    - name: Blokuoti ICMP echo užklausas 
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: DROP

    - name: Leisti output srautą (SSH, HTTP, HTTPS, syslog TCP)
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 5614

    - name: Leisti išeinantį UDP syslog srautą
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 514
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT

    - name: Registruoti atmestus paketus įeinančiame sraute
      iptables:
        chain: INPUT
        jump: LOG
        log_prefix: "Dropped INPUT: "
        log_level: 4

#    - name: Blokuoti visą input srautą
 #     iptables:
  #      chain: INPUT
   #     jump: DROP

    - name: Registruoti atmestus paketus output sraute
      iptables:
        chain: OUTPUT
        jump: LOG
        log_prefix: "Dropped output: " 
        log_level: 4

#    - name: Blokuoti visą output srautą
 #     iptables:
  #      chain: OUTPUT
   #     jump: DROP

#    - name: Išsaugoti iptables taisykles
 #     command: netfilter-persistent save
