---
- name: Konfiguruojam iptables su states
  hosts: test
  become: true
  tasks:
    - name: Flush existing iptables rules
      iptables:
        flush: yes

    - name: Allow established and related connections
      iptables:
        chain: INPUT
        match: state
        state: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow incoming (SSH, HTTP, HTTPS, ZABBIX AGENT)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: state
        state: NEW
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 10050

    - name: Log incoming ICMP echo requests (type 8)
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: LOG
        log_prefix: "ICMP Echo Request: "
        log_level: 4

    - name: Block echo request (ICMP type 8)
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: DROP

    - name: Allow outgoing traffic (SSH, HTTP, HTTPS, syslog TCP)
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: state
        state: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 5614

    - name: Allow outgoing UDP syslog traffic
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 514
        jump: ACCEPT

    - name: Log dropped packets in INPUT chain
      iptables:
        chain: INPUT
        jump: LOG
        log_prefix: "Dropped Packet in: "
        log_level: 4

    - name: Drop all incoming traffic
      iptables:
        chain: INPUT
        jump: DROP

    - name: Log dropped packets in OUTPUT chain
      iptables:
        chain: OUTPUT
        jump: LOG
        log_prefix: "Dropped Packet out: "
        log_level: 4

    - name: Drop all outgoing traffic
      iptables:
        chain: OUTPUT
        jump: DROP

    - name: Save iptables rules
      command: netfilter-persistent save
