- name: Konfiguruojam iptables su states
  hosts: test
  become: true
  tasks:
    - name: Flush existing iptables rules
      iptables:
        flush: yes

    - name: Allow incoming HTTP and HTTPS traffic
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: state
        state: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 10050

    - name: Allow incoming HTTP and HTTPS traffic
      iptables:
        chain: INPUT
        protocol: ICMP
        match: state
        state: NEW,ESTABLISHED
        jump: ACCEPT

    - name: Allow outgoing traffic (SSH, HTTP, HTTPS, syslog)
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: state
        state: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 5614

    - name: Allow outgoing traffic (syslog udp)
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: "{{ item }}"
        match: state
        state: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 514

    - name: Drop all įeinantį traficą
      iptables:
        chain: INPUT
        jump: DROP

    - name: Drop all išeinantį traficą
      iptables:
        chain: OUTPUT
        jump: DROP

    - name: Log dropped packets
      iptables:
        chain: INPUT
        jump: LOG
        log_prefix: "Dropped Packet in: "
        log_level: 4

    - name: Log dropped packets
      iptables:
        chain: OUTPUT
        jump: LOG
        log_prefix: "Dropped Packet out: "
        log_level: 4

    - name: Save iptables rules
      command: netfilter-persistent save
