- name: Konfiguruojam iptables su states
  hosts: test
  become: true
  tasks:
    - name: Flush existing iptables rules
      iptables:
        flush: yes

    - name: Allow incoming (SSH,HTTP,HTTPS, ZABBIX AGENT)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: state
        state: NEW,ESTABLISHED
        action: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 10050

    - name: Allow incoming ICMP
      iptables:
        chain: INPUT
        protocol: ICMP
        match: icmp
        icmp_type: echo-reply
        action: ACCEPT


    - name: Block echo request (ICMP type 8)
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        action: DROP

    - name: Allow outgoing traffic (SSH, HTTP, HTTPS, syslog)
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: state
        state: NEW,ESTABLISHED
        action: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 5614

    - name: Allow outgoing traffic (syslog udp)
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: "{{ item }}"
        match: state
        state: NEW,ESTABLISHED
        action: ACCEPT
      loop:
        - 514

    - name: Drop all įeinantį traficą
      iptables:
        chain: INPUT
        action: DROP

    - name: Drop all išeinantį traficą
      iptables:
        chain: OUTPUT
        action: DROP

    - name: Log dropped packets
      iptables:
        chain: INPUT
        action: LOG
        log_prefix: "Dropped Packet in: "
        log_level: 4

    - name: Log dropped packets
      iptables:
        chain: OUTPUT
        action: LOG
        log_prefix: "Dropped Packet out: "
        log_level: 4

    - name: Save iptables rules
      command: netfilter-persistent save
