- name: Konfigūruoti iptables su būsenomis ir įjungti Wazuh Agent prievadus
  hosts: test
  become: true
  tasks:
    - name: Ištrinti default policies
      iptables:
        chain: "{{ item }}"
        policy: ACCEPT
      loop:
        - INPUT
        - OUTPUT
        - FORWARD

    - name: Išvalyti esamas iptables taisykles
      iptables:
        flush: yes

    - name: Leisti input ryšius (SSH, HTTP, HTTPS, ZABBIX AGENT, WAZUH AGENT)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 10050

    - name: Leisti output srautą (SSH, HTTP, HTTPS, syslog TCP, WAZUH AGENT)
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 5614
        - 1514
        - 1515

    - name: Leisti output DNS TCP
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 53
        jump: ACCEPT

    - name: Leisti output DNS TCP
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: 53
        match: conntrack
        ctstate: NEW
        jump: ACCEPT

    - name: Leisti input ir output srautą ESTABLISHED
      iptables:
        chain: "{{ item }}"
        match: conntrack
        ctstate: ESTABLISHED
        jump: ACCEPT
      loop:
        - INPUT
        - OUTPUT

    - name: Leisti ICMP echo-request iš specifinio IP
      iptables:
        chain: INPUT
        protocol: icmp
        icmp_type: echo-request
        source: 192.168.193.100
        match: conntrack
        ctstate: NEW
        jump: ACCEPT

    - name: Leisti output UDP syslog srautą
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 514
        jump: ACCEPT

    - name: Default policy INPUT block all
      iptables:
        chain: INPUT
        policy: DROP

    - name: Default policy OUTPUT block all
      iptables:
        chain: OUTPUT
        policy: DROP

    - name: Default policy FORWARD block all
      iptables:
        chain: FORWARD
        policy: DROP

    - name: Monitoring atmestus paketus
      iptables:
        chain: "{{ item }}"
        jump: LOG
        log_prefix: "Dropped {{ item }}: "
        log_level: 1
      loop:
        - INPUT
        - OUTPUT

    - name: Išsaugoti iptables taisykles
      command: netfilter-persistent save
