---
- name: Konfigūruoti iptables su būsenomis
  hosts: test
  become: true
  tasks:
    - name: Išvalyti esamas iptables taisykles
      iptables:
        flush: yes

    - name: Leisti input ryšius (SSH, HTTP, HTTPS, ZABBIX AGENT)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 10050

    - name: Leisti output ICMP echo-replay
      iptables:
        chain: OUTPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-reply
        jump: ACCEPT   

    - name: Log input ICMP echo užklausas
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: LOG
        log_prefix: "ICMP Echo request: "
        log_level: 4

    - name: Blokuoti ICMP echo užklausas 
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: DROP


    - name: Leisti output srautą ESTABLISHED
      iptables:
        chain: OUTPUT
        match: conntrack
        ctstate: ESTABLISHED
        jump: ACCEPT

    - name: Leisti output srautą (SSH, HTTP, HTTPS, syslog TCP)
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 5614

    - name: Leisti output UDP syslog srautą
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 514
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT

    - name: Monitoring atmestus paketus input sraute
      iptables:
        chain: INPUT
        jump: LOG
        log_prefix: "Dropped INPUT: "
        log_level: 4

    - name: Default policy INPUT block all
      iptables:
        chain: INPUT
        policy: DROP

    - name: Monitoring atmestus paketus output sraute
      iptables:
        chain: OUTPUT
        jump: LOG
        log_prefix: "Dropped output: " 
        log_level: 4

    - name: Default policy OUTPUT block all
      iptables:
        chain: OUTPUT
        policy: DROP

    - name: Default policy OUTPUT block all
      iptables:
        chain: FORWARD
        policy: DROP


  #  - name: Išsaugoti iptables taisykles
 #     command: netfilter-persistent save
