---
- name: Konfigūruoti iptables su būsenomis
  hosts: test
  become: true
  tasks:
    - name: Išvalyti esamas iptables taisykles
      iptables:
        flush: yes

    - name: Leisti įeinančius ryšius (SSH, HTTP, HTTPS, ZABBIX AGENT)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 10050

    - name: Log įeinančius ICMP echo užklausas (tipas 8)
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: LOG
        log_prefix: "ICMP Echo Užklausa: "
        log_level: 4

    - name: Blokuoti ICMP echo užklausas (tipas 8)
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp
        icmp_type: echo-request
        jump: DROP

    - name: Leisti išeinantį srautą (SSH, HTTP, HTTPS, syslog TCP)
      iptables:
        chain: OUTPUT
        protocol: tcp
        destination_port: "{{ item }}"
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
      loop:
        - 22
        - 80
        - 443
        - 5614

    - name: Leisti išeinantį UDP syslog srautą
      iptables:
        chain: OUTPUT
        protocol: udp
        destination_port: 514
        match: conntrack
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT

    - name: Registruoti atmestus paketus įeinančiame sraute
      iptables:
        chain: INPUT
        jump: LOG
        log_prefix: "Atmestas paketas (įėjimas): "
        log_level: 4

    - name: Blokuoti visą įeinantį srautą
      iptables:
        chain: INPUT
        jump: DROP

    - name: Registruoti atmestus paketus išeinančiame sraute
      iptables:
        chain: OUTPUT
        jump: LOG
        log_prefix: "Atmestas paketas (išėjimas): "
        log_level: 4

    - name: Blokuoti visą išeinantį srautą
      iptables:
        chain: OUTPUT
        jump: DROP

#    - name: Išsaugoti iptables taisykles
 #     command: netfilter-persistent save
