---
- name: Install MySQL
  hosts: test
  become: yes
  become_method: sudo
  
  tasks:
    - name: Include encrypted vars
      ansible.builtin.include_vars:
        file: /etc/ansible/secrets.yml

    - name: Debugging all secrets
      debug:
        var: secrets

    - name: Install MySQL reikalingus paketus
      package:
        name:
          - python3-pip
          - python3-mysqldb
          - python3-pymysql   
        state: present

    - name: Install MySQL Server
      package:
        name: "{{ 'mysql-server' if ansible_os_family == 'RedHat' else 'mariadb-server' }}"
        state: present

    - name: Start MySQL
      service:
        name: "{{ 'mysqld' if ansible_os_family == 'RedHat' else 'mysql' }}"
        state: started
        enabled: yes
        
    - name: Root slaptažodis
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: "*.*:ALL,GRANT"
      ignore_errors: yes

    - name: Panaikinti root
      mysql_user:
        name: root
        host: "%"
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"
      ignore_errors: yes

    - name: Sukurti nauja admin vartotoja
      mysql_user:
        name: "{{ mysql_admin_user }}"
        password: "{{ mysql_admin_password }}"
        host: "%"
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Panaikinti root
      mysql_user:
        name: root
        state: absent
        login_user: "{{ mysql_admin_user }}"
        login_password: "{{ mysql_admin_password }}"
      ignore_errors: yes

    - name: Kurti MySQL duombaze
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: "{{ mysql_admin_user }}"
        login_password: "{{ mysql_admin_password }}"

    - name: Kurti MySQL duombazes vartotoją su tinklo apribojomu
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        host: "{{ allowed_subnet }}"
        priv: "{{ db_name }}.*:ALL"
        state: present
        login_user: "{{ mysql_admin_user }}"
        login_password: "{{ mysql_admin_password }}"

    - name: Restart MySQL
      service:
        name: "{{ 'mysqld' if ansible_os_family == 'RedHat' else 'mysql' }}"
        state: restarted
