---
- name: Add users and secure SSH
  hosts: test
  become: yes
  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: /bin/bash
        create_home: yes
      loop:
        - { username: "bandomasis1" }
        - { username: "bandomasis2" }

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0700'
      loop:
        - { username: "bandomasis1" }
        - { username: "bandomasis2" }

    - name: Add SSH keys to authorized_keys
      ansible.builtin.copy:
        content: "{{ item.ssh_key }}"
        dest: "/home/{{ item.username }}/.ssh/authorized_keys"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0600'
      loop:
        - { username: "bandomasis1", ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1Jyt5RQo+Pa67s05Noq3A/Xg8pprdm6PNqz0HF3Ljh bandomasis1" }
        - { username: "bandomasis2", ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEPeYDzPA79lxmRAqW1/xhq7LdbJsu4dywtPEIhsW2A bandomasis2" }

  #  - name: Disable password authentication in SSH
   #   ansible.builtin.lineinfile:
    #    path: /etc/ssh/sshd_config
     #   regexp: '^PasswordAuthentication'
      #  line: 'PasswordAuthentication no'
      #notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
