---
- name: Install ESET RDSensor and Check Status
  hosts: web
  become: yes
  tasks:
    - name: Download ESET RDSensor installation script
      get_url:
        url: https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh
        dest: /tmp/rdsensor-linux-x86_64.sh
        mode: '0755'

    - name: Make the installation script executable
      command: chmod +x /tmp/rdsensor-linux-x86_64.sh

    - name: Install ESET RDSensor using expect to handle user input
      expect:
        command: /tmp/rdsensor-linux-x86_64.sh
        responses:
          # Simulate pressing Ctrl+C to interrupt the first message (usually disclaimer)
          "Press Ctrl+C to interrupt": "\003"
          # Automatically respond 'y' to accept the license agreement
          "Do you accept the license? [y/N]": "y"
          # Automatically respond 'Y' to participate in the Product Improvement Program
          "Do you want to participate in the Product improvement program? [Y/n]": "Y"
      become: yes
      args:
        creates: /opt/eset/RemoteDeviceSensor

    - name: Clean up installation script
      file:
        path: /tmp/rdsensor-linux-x86_64.sh
        state: absent

    - name: Check if ESET RDSensor service is running
