---
- name: Install ESET RD Sensor on Linux
  hosts: test
  become: true
  become_method: sudo
  tasks:

    - name: Parsisiunciam ESET RD sensor
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: 
      file:
        path: /tmp/rdsensor-linux-x86_64.sh
        mode: '0755'

    - name: Įrašinėjam
      command: bash /tmp/rdsensor-linux-x86_64.sh
      args:
        chdir: /tmp

    - name: Ensure ESET RD Sensor service is running
      systemd:
        name: eset-rd-sensor
        state: started
        enabled: yes
      ignore_errors: yes  # Ignore errors in case the service name varies
