---
- name: Install ESET RD Sensor
  hosts: web
  become: true
  tasks:

    - name: Download RD sensor
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: RD Sensor installation file as an executable
      command: "chmod +x /tmp/rdsensor-linux-x86_64.sh" && "bash /tmp/rdsensor-linux-x86_64.sh --skip-license  --disable-imp-program"

  #  - name: Vykdyti RDsensor installer su 
   #   command: "/tmp/rdsensor-linux-x86_64.sh --skip-license  --disable-imp-program"

    - name: Patikrinam ar RDsensorius veikia
      systemd:
        name: rdsensor
        state: started
        enabled: yes

    - name: Patikrinam statusą RDsensor
      command: systemctl status rdsensor
      register: rdsensor_status
      changed_when: false

    - name: Show RD Sensor service status
      debug:
        msg: "{{ rdsensor_status.stdout }}"
