---
- name: Install ESET RDSensor and Check Status
  hosts: web
  become: yes
  tasks:
    - name: Download ESET RDSensor installation script
      get_url:
        url: https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh
        dest: /tmp/rdsensor-linux-x86_64.sh
        mode: '0755'

    - name: Install ESET RDSensor
      command: /bin/bash /tmp/rdsensor-linux-x86_64.sh --install
      args:
        creates: /opt/eset/RemoteDeviceSensor

    - name: Clean up installation script
      file:
        path: /tmp/rdsensor-linux-x86_64.sh
        state: absent

    - name: Check if ESET RDSensor service is running
      systemd:
        name: esets
        state: started
      register: rdsensor_status
      ignore_errors: yes

    - name: Display ESET RDSensor service status
      debug:
        msg: "ESET RDS
