---
- name: Install ESET RD Sensor on Linux
  hosts: test
  become: yes
  tasks:

    - name: Install required dependencies
      package:
        name:
          - wget
          - curl
          - systemd
        state: present

    - name: Download ESET RD Sensor installation script
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: Ensure script is executable
      file:
        path: /tmp/rdsensor-linux-x86_64.sh
        mode: '0755'

    - name: Run the installation script and auto-accept agreement
      command: echo "yes" | bash /tmp/rdsensor-linux-x86_64.sh
      register: install_output
      ignore_errors: yes

    - name: Print installation script output
      debug:
        var: install_output.stdout_lines

    - name: Ensure ESET RD Sensor service is running
      systemd:
        name: eset-rdsensor
        state: started
        enabled: yes
      ignore_errors: yes
