---
- name: Install ESET RD Sensor
  hosts: test
  become: yes
  tasks:

    - name: Download RD Sensor installer
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: Set RD Sensor installer as executable
      command: chmod +x /tmp/rdsensor-linux-x86_64.sh
      args:
        creates: /tmp/rdsensor-linux-x86_64.sh

    - name: Run ESET RD Sensor installer with EULA and Product Improvement prompts
      expect:
        command: "/tmp/rdsensor-linux-x86_64.sh"
        responses:
          # Respond to the EULA prompt (Space to continue, Y to accept)
          'Press Space to continue': ' '
          'Do you accept the license agreement?': 'Y'
          'Do you wish to participate in the product improvement program?': 'Y'
      args:
        chdir: /tmp

    - name: Ensure ESET RD Sensor is running
      systemd:
        name: rdsensor
        state: started
        enabled: yes

    - name: Verify RD Sensor service status
      command: systemctl status rdsensor
      register: rdsensor_status
      changed_when: false

    - name: Show RD Sensor service status
      debug:
        msg: "{{ rdsensor_status.stdout }}"
