- hosts: test
  become: yes
  tasks:
    - name: Ensure necessary tools are installed
      apt:
        name:
          - curl
          - expect
        state: present

    - name: Download the RD Sensor installation script
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: Create Expect script for automated installation
      copy:
        dest: "/tmp/install_rdsensor.exp"
        content: |
          #!/usr/bin/expect -f
          spawn sudo /tmp/rdsensor-linux-x86_64.sh
          expect "Do you accept the agreement?" { send "Y\r" }
          expect "Do you agree to participate?" { send "Y\r" }
          expect eof

    - name: Make Expect script executable
      command: chmod +
