- hosts: web
  become: yes
  tasks:
    - name: Ensure necessary tools are installed
      apt:
        name: curl
        state: present

    - name: Download the RD Sensor installation script
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: Copy Bash script to install RD Sensor
      copy:
        src: ./install_rdsensor.sh
        dest: /tmp/install_rdsensor.sh
        mode: '0755'

    - name: Run the Bash script to install RD Sensor
      command: /tmp/install_rdsensor.sh

    - name: Reload systemd manager configuration
      command: sudo systemctl daemon-reload

    - name: Start and enable the RD Sensor service
      service:
        name: rdsensor
        state: started
        enabled: yes
