---
- name: Install ESET RD Sensor
  hosts: web
  become: true
  tasks:

    - name: Install pexpect Python library
      package:
        name: python3-pexpect
        state: present

    - name: Download RD Sensor installer
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: Set RD Sensor installer as executable
      command: chmod +x /tmp/rdsensor-linux-x86_64.sh
      args:
        creates: /tmp/rdsensor-linux-x86_64.sh

    - name: Run ESET RD Sensor installer with EULA and Product Improvement prompts
      expect:
        command: "/tmp/rdsensor-linux-x86_64.sh"
        responses:
          # If the installer prompts "More--", press 'q' to quit
          'More--': 'q\n'
          # Accept the license agreement
          'Do you accept the license?': 'Y\n'
          # Accept the product improvement program
          'Do you want to participate in the Product improvement program?': 'Y\n'
        timeout: 10  # Increased timeout to 20 minutes (1200 seconds)
      args:
        chdir: /tmp

    - name: Ensure ESET RD Sensor is running
      systemd:
        name: rdsensor
        state: started
        enabled: yes

    - name: Verify RD Sensor service status
      command: systemctl status rdsensor
      register: rdsensor_status
      changed_when: false

    - name: Show RD Sensor service status
      debug:
        msg: "{{ rdsensor_status.stdout }}"
