---
- name: Install ESET RD Sensor on Linux
  hosts: test
  become: yes
  tasks:

    # Install required dependencies including expect
    - name: Install required dependencies
      package:
        name:
          - wget
          - curl
          - expect
          - python3-pip
          - systemd
        state: present

    # Download the ESET RD Sensor installation script
    - name: Download ESET RD Sensor installation script
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    # Ensure the installation script is executable
    - name: Ensure script is executable
      file:
        path: /tmp/rdsensor-linux-x86_64.sh
        mode: '0755'

    # Run the installation script, simulate Ctrl+C to stop reading the rules, then accept agreements
    - name: Run the installation script and automatically accept prompts
      expect:
        command: bash /tmp/rdsensor-linux-x86_64.sh
        responses:
          # Simulate pressing <Ctrl+C> to stop reading the license
          "Do you accept the license? [y/N]": "y"
          "Do you want to participate in the Product improvement program? [Y/n]": "y"
          "Do you want to continue with the installation? [y/N]": "y"
        timeout: 600

    # Print installation log output for debugging
    - name: Print installation log
      debug:
        var: install_output.stdout_lines

    # Ensure ESET RD Sensor service is running
    - name: Ensure ESET RD Sensor service is running
      systemd:
        name: rdsensor
        state: started
        enabled: yes
      ignore_errors: yes
