---
- name: Install ESET RD Sensor
  hosts: test
  become: true
  tasks:

    - name: Install pexpect Python library
      package:
        name: python3-pexpect
        state: present

    - name: Download RD Sensor installer
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: Set RD Sensor installer as executable
      command: chmod +x /tmp/rdsensor-linux-x86_64.sh
      args:
        creates: /tmp/rdsensor-linux-x86_64.sh

    - name: Run ESET RD Sensor installer with EULA and Product Improvement prompts
      expect:
        command: "/tmp/rdsensor-linux-x86_64.sh"
        responses:
          # Send Ctrl+C (escape sequence \003) to interrupt the extraction process
          'If you want to stop extracting, please press <ctrl-C>.': '\003\n'
          # If the installer prompts "More--", press Enter to continue
          'More--': '\n'
          # Accept the license agreement
          'Do you accept the license agreement?': 'Y\n'
          # Accept the product improvement program
          'Do you wish to participate in the product improvement program?': 'Y\n'
        time
