---
- name: Install ESET RD Sensor
  hosts: web
  become: true
  tasks:

    - name: Instaliuojam python3-pexpect
      package:
        name: python3-pexpect
        state: present

    - name: Download RD sensor
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: RD Sensor installation file as an executable
      command: chmod +x /tmp/rdsensor-linux-x86_64.sh
   #   args:
    #    creates: /tmp/rdsensor-linux-x86_64.sh

    - name: Vykdyti RDsensor installer su 
      expect:
        command: "/tmp/rdsensor-linux-x86_64.sh"
        responses:
          'More--': 'q\n'
          'Do you accept the license?': 'Y\n'
          'Do you want to participate in the Product improvement program?': 'N\n'
   #   args:
  #      chdir: /tmp

    - name: Patikrinam ar RDsensorius veikia
      systemd:
        name: rdsensor
        state: started
        enabled: yes

    - name: Patikrinam statusą RDsensor
      command: systemctl status rdsensor
      register: rdsensor_status
      changed_when: false

    - name: Show RD Sensor service status
      debug:
        msg: "{{ rdsensor_status.stdout }}"
