---
- name: Install ESET RDSensor and Check Status
  hosts: web
  become: yes
  tasks:
    - name: Download
      get_url:
        url: https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh
        dest: /tmp/rdsensor-linux-x86_64.sh
        mode: '0755'

    - name: Padarom pasiekiama
      command: chmod +x /tmp/rdsensor-linux-x86_64.sh

    - name: Install RDsensor su sutikimu
      expect:
        command: /tmp/rdsensor-linux-x86_64.sh
        responses:
          "If you want to stop extracting, please press <ctrl-C>": "\003"  # \003 is the Ctrl+C
          
          "Press any key to continue": "\n"  

          "Do you accept the license? [y/N]": "y"
          '
          "Do you want to participate in the Product improvement program? [Y/n]": "Y"

      become: yes
      args:
        creates: /opt/eset/RemoteDeviceSensor

    - name: Ištrinam install failą
      file:
        path: /tmp/rdsensor-linux-x86_64.sh
        state: absent

    - name: Patikrinam ar veikia RDsensor
      systemd:
        name: esets
        state: started
      register: rdsensor_status
      ignore_errors: yes

    - name: Atvaizduojam statusą
      debug:
        msg: "ESET RDsensor aktyvus {{ rdsensor_status.status.ActiveState }}"
      when: rdsensor_status is defined and rdsensor_status.status is defined

    - name: Patikrinam ar RDsensor instaliuotas
      stat:
        path: /opt/eset/RemoteDeviceSensor
      register: rdsensor_installed

    - name: Instaliacijos statusas
      debug:
        msg: "ESET RDsensor instaliuotas at /opt/eset/RemoteDeviceSensor"
      when: rdsensor_installed.stat.exists
