---
- name: Install ESET RD Sensor
  hosts: all
  become: yes
  tasks:

    - name: Install pexpect Python library
      package:
        name: python3-pexpect
        state: present

    - name: Download RD Sensor installer
      get_url:
        url: "https://download.eset.com/com/eset/apps/business/era/rdsensor/latest/rdsensor-linux-x86_64.sh"
        dest: "/tmp/rdsensor-linux-x86_64.sh"
        mode: '0755'

    - name: Set RD Sensor installer as executable
      command: chmod +x /tmp/rdsensor-linux-x86_64.sh
      args:
        creates: /tmp/rdsensor-linux-x86_64.sh

    - name: Run ESET RD Sensor installer with EULA and Product Improvement prompts
      expect:
        command: "/tmp/rdsensor-linux-x86_64.sh"
        responses:
          # Simulate pressing Ctrl+C (escape sequence \003) followed by Enter (\n)
          'If you want to stop extracting, please press <ctrl-C>.': '\003\n'
          'Do you accept the license agreement?': 'Y\n'
          'Do you wish to participate in the product improvement program?': 'Y\n'
        timeout: 100  # Increase timeout to ensure the process has enough time
      args:
        chdir: /tmp

    - name: Ensure ESET RD Sensor is running
      systemd:
        name: rdsensor
        state: started
        enabled: yes

    - name: Verify RD Sensor service status
      command: systemctl status rdsensor
      register: rdsensor_status
      changed_when: false

    - name: Show RD Sensor service status
      debug:
        msg: "{{ rdsensor_status.stdout }}"
