---
- name: Atvaizduojami praleisti portai iptables
  hosts: test
  become: yes
  tasks:

    - name: Gaunamos iptables taisykles
      command: iptables -L INPUT -v -n
      register: input_rules
      changed_when: false

    - name: Gaunamos iptables taisykles
      command: iptables -L OUTPUT -v -n
      register: output_rules
      changed_when: false

    - name: Rodomi incoming praleisti portai
      debug:
        msg: "{{ input_rules.stdout_lines | select('search', 'ACCEPT') | list }}"

    - name: Rodomi outgoing praleisti portai
      debug:
        msg: "{{ output_rules.stdout_lines | select('search', 'ACCEPT') | list }}"
