---
- name: Sukurti vartotojus, prisijungimas tik su SSH
  hosts: test
  become: yes
  tasks:
    - name: Add users
      ansible.builtin.user:
        name: "{{ item.username }}"
        shell: /bin/bash
        create_home: yes
      loop:
        - { username: "bandomasis1" }
        - { username: "bandomasis2" }

    - name: Tikrinu direktorija
      ansible.builtin.file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0700'
      loop:
        - { username: "bandomasis1" }
        - { username: "bandomasis2" }

    - name: Pridedu SSH raktus
      ansible.builtin.copy:
        content: "{{ item.ssh_key }}"
        dest: "/home/{{ item.username }}/.ssh/authorized_keys"
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0600'
      loop:
        - { username: "bandomasis1", ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1Jyt5RQo+Pa67s05Noq3A/Xg8pprdm6PNqz0HF3Ljh bandomasis1" }
        - { username: "bandomasis2", ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOEPeYDzPA79lxmRAqW1/xhq7LdbJsu4dywtPEIhsW2A bandomasis2" }

    - name: Pridedu vartotojus į sudo grupę
      ansible.builtin.user:
        name: "{{ item.username }}"
        groups: sudo
        append: yes
      loop:
        - { username: "bandomasis1" }
        - { username: "bandomasis2" }

    - name: Leidžiu vartotojams vykdyti sudo be slaptažodžio
      ansible.builtin.copy:
        content: "{{ item.username }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ item.username }}"
        mode: '0440'
      loop:
        - { username: "bandomasis1" }
        - { username: "bandomasis2" }

    - name: Pasalinu prisijungima naudojant slaptažodį
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      notify: Restart SSH

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
