- name: Install Zabbix Agent 2 (7.2)
  hosts: test
  become: yes  

  tasks:
    - name: Include encrypted vars
      ansible.builtin.include_vars:
        file: /etc/ansible/zabbix_vars.yml

    
    - name: Download zabbix 7.2 repository
      get_url:
        url: "https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb"
        dest: "/tmp/zabbix-release_latest_7.2+debian12_all.deb"

    
    - name: Install repository .deb
      command: dpkg -i /tmp/zabbix-release_latest_7.2+debian12_all.deb
      become: yes


    - name: Install Zabbix Agent 2 7.2
      apt:
        name: zabbix-agent2
        state: present
        update_cache: yes

    - name: Start Zabbix Agent 2 service to create the configuration file
      systemd:
        name: zabbix-agent2
        state: started
        enabled: yes

    # Wait for a moment to ensure the configuration file has been created
    - name: Wait for the configuration file to be created
      wait_for:
        path: /etc/zabbix/zabbix_agent2.conf
        state: present
        delay: 5
        timeout: 30


    - name: Nustatom zabbix serverio IP 
      lineinfile:
        path: "/etc/zabbix/zabbix_agent2.conf"
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"


    - name: Zabbix agento hostname
      lineinfile:
        path: "/etc/zabbix/zabbix_agent2.conf"
        regexp: '^Hostname='
        line: "Hostname={{ ansible_hostname }}"

    - name: Igalinam PSK encryption  
      block:
        - name: Set TLSConnect=psk in the Zabbix agent configuration
          lineinfile:
            path: "/etc/zabbix/zabbix_agent2.conf"
            regexp: '^TLSConnect='
            line: "TLSConnect=psk"
            create: yes

        - name: Set TLSAccept=psk in the Zabbix agent configuration
          lineinfile:
            path: "/etc/zabbix/zabbix_agent2.conf"
            regexp: '^TLSAccept='
            line: "TLSAccept=psk"
            create: yes

    - name: Sukuriam PSK zabbix useriui
      copy:
        dest: "/etc/zabbix/zabbix_agentd.psk"
        content: "{{ psk_key }}"
        owner: zabbix
        group: zabbix
        mode: '0600'

    - name: Konfiguruojam zabbix konfiga
      block:
        - name: Set TLSPSKIdentity in the Zabbix agent configuration
          lineinfile:
            path: "/etc/zabbix/zabbix_agent2.conf"
            regexp: '^TLSPSKIdentity='
            line: "TLSPSKIdentity={{ psk_identity }}"
            create: yes

        - name: Konfiguruojam zabbix konfiga 
          lineinfile:
            path: "/etc/zabbix/zabbix_agent2.conf"
            regexp: '^TLSPSKFile='
            line: "TLSPSKFile=/etc/zabbix/zabbix_agentd.psk"
            create: yes

    - name: Restart Zabbix Agent 2 service
      systemd:
        name: zabbix-agent2
        state: restarted
        enabled: yes
