- name: Install Zabbix Agent 2 LTS (7.0) on Debian, Ubuntu, or Fedora
  hosts: test2
  become: yes
  vars:
    debian_repo_url: "https://repo.zabbix.com/zabbix/7.0/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.0+{{ ansible_distribution_release }}_all.deb"
    ubuntu_repo_url: "https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+{{ ansible_distribution_release }}_all.deb"
    fedora_repo_url: "https://repo.zabbix.com/zabbix/7.0/rhel/8/x86_64/zabbix-release-7.0-1.el8.noarch.rpm"

  tasks:
    - name: Install prerequisites for Debian/Ubuntu
      apt:
        name: apt-transport-https
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Zabbix repo for Debian
      get_url:
        url: "{{ debian_repo_url }}"
        dest: "/tmp/zabbix-release_7.0.deb"
      when: ansible_distribution == 'Debian'

    - name: Download Zabbix repo for Ubuntu
      get_url:
        url: "{{ ubuntu_repo_url }}"
        dest: "/tmp/zabbix-release_7.0.deb"
      when: ansible_distribution == 'Ubuntu'

    - name: Install Zabbix repo (Debian/Ubuntu)
      apt:
        deb: "/tmp/zabbix-release_7.0.deb"
      when: ansible_os_family == "Debian"

    - name: Download Zabbix repo for Fedora
      get_url:
        url: "{{ fedora_repo_url }}"
        dest: "/tmp/zabbix-release_7.0.rpm"
      when: ansible_distribution == 'Fedora'

    - name: Install Zabbix repo (Fedora)
      dnf:
        name: "/tmp/zabbix-release_7.0.rpm"
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Update package cache (Fedora)
      dnf:
        update_cache: yes
      when: ansible_distribution == 'Fedora'

    - name: Install Zabbix Agent 2 (Debian/Ubuntu)
      apt:
        name: zabbix-agent2
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Zabbix Agent 2 (Fedora)
      dnf:
        name: zabbix-agent2
        state: present
        update_cache: yes
      when: ansible_distribution == 'Fedora'

    - name: Enable and start Zabbix Agent 2
      systemd:
        name: zabbix-agent2
        state: started
        enabled: yes

    - name: Wait for the config file to exist
      wait_for:
        path: /etc/zabbix/zabbix_agent2.conf
        state: present
        delay: 5
        timeout: 30

    - name: Set Zabbix Server IP
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Server='
        line: "Server=zabbix.bp.lt"

    - name: Set Zabbix ServerActive address
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^ServerActive='
        line: "ServerActive=zabbix.bp.lt"

    - name: Set Zabbix Agent hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '^Hostname='
        line: "Hostname={{ ansible_hostname }}"

    - name: Restart Zabbix Agent 2 to apply changes
      systemd:
        name: zabbix-agent2
        state: restarted
